### ISSUE TITLE
Add plugin metadata key for used kernel version

### ISSUE THREAD

**Issue by frzb** [frzb/coinboot#49]
The current metadata structure of the plugin creation files looks like this:

```
plugin: AMDGPU-Pro Polaris
archive_name: amdgpupro_polaris
version: 20.50-1234664
description: AMD Polaris GPU (RX500/RX400 family) firmware and driver with support for OpenCL 1.2
maintainer: Gunter Miegel <gunter.miegel@coiboot.io>
source: https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-50
run: |
  < pluging creation code>
```
As Coinboot progresses we might bring up multiple kernel versions like `5.11.0-46-generic` or `5.13.0-25-generic`. 
For the plugins  that have a kernel dependency we have to reflect that in plugin metadata with adding the mandatory key `kernel`.
For the plugins that don't have a kernel dependency I purpose to set `kernel` to the value `all`.

**Comment by frzb** [comment]
Code for detecting the kernel version and use is at as prefix for the composing of the  S3 object URL is already there:

https://github.com/frzb/coinboot/blob/2634c81d1968df879b440e1f8f05fd084d2f90e9/plugins/coinbootmaker_helper#L212-L227

**Comment by lookfirst** [comment]
>  I purpose to set kernel to the value all.

What if the key is undefined?
